# Generated by Django 3.1.7 on 2021-03-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('entry', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('entry_Name', models.CharField(max_length=20)),
                ('protein_names', models.CharField(max_length=500)),
                ('locations', models.TextField()),
                ('function', models.TextField()),
                ('organism', models.CharField(max_length=5)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
