# Generated by Django 3.1.7 on 2021-04-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0003_auto_20210407_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protein',
            options={'verbose_name_plural': 'proteins'},
        ),
    ]
