# Generated by Django 3.1.7 on 2021-04-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0004_auto_20210407_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proteins.protein')),
            ],
        ),
    ]
