# Generated by Django 3.1.7 on 2021-04-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0006_auto_20210407_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteinimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
