# Generated by Django 3.1.7 on 2021-04-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0007_auto_20210407_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteinimage',
            old_name='protein',
            new_name='protein_id',
        ),
        migrations.AlterField(
            model_name='proteinimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
