# Generated by Django 3.1.7 on 2021-04-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0008_auto_20210408_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteinimage',
            old_name='image',
            new_name='images',
        ),
    ]
